
spring:
  datasource:
    password: jimbo1234
    url: jdbc:mysql://localhost:3306/serverdb
    username: jim
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
